name: fort-tag-scanner
version: "0.2.2"
summary:  A Tag Scanner for the FORmicidae Tracker
description: |
  fort-tag-scanner is a small graphical application that uses a webcam
  to scan tags, and report them in a CSV. It can also load a myrmidon
  file to match automatically AntID from the scanned tags.
base: core20
confinement: strict
parts:
  myrmidon:
    plugin: cmake
    source-type: git
    source: https://github.com/formicidae-tracker/studio.git
    source-commit: 9c6e411c655cc6f24967c90989be57bd308e31e1
    build-packages:
      - g++
      - make
      - git
      - libeigen3-dev
      - libopencv-dev
      - libprotobuf-dev
      - protobuf-compiler
      - qtbase5-dev
      - libasio-dev
      - libboost-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    stage:
      - usr/include/apriltag/
      - usr/include/fort/
      - usr/lib/libfort-*
      - usr/lib/FortMyrmidon
      - usr/lib/FortHermesCpp
      - usr/lib/FortTags
  tag-scanner:
    plugin: cmake
    source-type: git
    source: https://github.com/formicidae-tracker/tag-scanner.git
    source-tag: v0.2.2
    build-packages:
      - qtmultimedia5-dev
      - libqt5multimedia5-plugins
    stage-packages:
      - libqt5widgets5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libopencv-videoio4.2
      - libprotobuf17
      - libpulse0
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - libglu1-mesa
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=/root/stage/usr/
    after:
      - myrmidon
apps:
  fort-tag-scanner:
    command: usr/bin/fort-tag-scanner
    environment:
      GST_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
      GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
      GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qt5/libs:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/"
      QT_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP_DESKTOP_RUNTIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP_DESKTOP_RUNTIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
#      QT_QPA_PLATFORMTHEME: "gtk3"
    plugs:
      - camera
      - home
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - opengl
